### ISSUE TITLE
Last Reboot Color Change

### ISSUE THREAD

**Issue by GenoMyb** [root3nl/SupportApp#10] opened 2021-03-16 11:35 UTC
Good day 
It would be great if after 5 days of no reboot that the user will also get an indication (1) in the app icon (like it does if you have an update ) and it will then display next to the Last reboot and if you hover over the last reboot, the text changes to "Please reboot device "

**Comment by jordywitteman** [comment] 2021-03-17 10:11
Hi Eugene,

This is definitely something that is on the roadmap and I think we will aim to have the admin set the amount of days before the item turns to another color and/or show the notification badge. Same plan for disk space available.

Thanks!

**Comment by boettchs** [comment] 2021-05-17 20:51
Interesting idea @GenoMyb! 
I came to report another bit with:
The "Last reboot" button shows **"5 hour since last reboot" as opposed to "5 hours since last reboot"**. Could this be added to upcoming fixes?
Thank you!

**Comment by jordywitteman** [comment] 2021-05-27 10:59
Hi @boettchs we have checked the example (5 hours) and could not reproduce the issue anymore. Should be fixed in 2.2. Thanks!

**Comment by boettchs** [comment] 2021-05-28 21:04
Hi Jordy,

See attached - “2 hour ago"
I greyed out company stuff…

I looked for 2.2, but only 2.1 shows on the download link?

Scott

**Comment by jordywitteman** [comment] 2021-05-31 07:28
Hi @boettchs, version 2.2 will probably be released this week

**Comment by sidbena** [comment] 2021-06-17 18:18
Sorry for slightly hijacking this issue, but I think it's very related.
Thanks for an awesome tool!
I like the new warning for when the `UptimeDaysLimit` has been reached, but I would love for the red menu bar badge to switch to a less intrusive color (perhaps blue?), when uptime has been surpassed, but still turn red when there is a more important warning, like an OS update available. Would that be possible? Hopefully it can be set as a setting too! Thanks again!

**Comment by jordywitteman** [comment] 2021-11-11 14:40
@GenoMyb I believe this one can be closed as the notification badge was introduced in 2.2

@sidbena we've chosen systemOrange as the color for these warnings and follow Apple's example, like on macOS Monterey when your mic/camera is active. This was added in 2.3. Hope you like it!

**Closed by jordywitteman** 2021-11-11 14:40 UTC
