### ISSUE TITLE
Hangs after 24 hours running on M1 Air

### ISSUE THREAD

**Issue by everetteallen** [root3nl/SupportApp#70] opened 2022-07-13 12:48 UTC
Consistently Support hangs on my M1 Air after running ~24 hours.  Clicking the menu bar icon gives the window with all information correctly displayed, but the buttons are not responsive and the window will not dismiss.

**Comment by jordywitteman** [comment] 2022-07-13 13:09
Hi @everetteallen would you happen to have some logs and a sample of your configuration profile? Are you using the new password integrations? Thanks!

**Comment by everetteallen** [comment] 2022-07-13 13:16
Example Crash Log:
Translated Report (Full Report Below)
-------------------------------------

Process:               Support [52471]
Path:                  /private/var/folders/*/Support.app/Contents/MacOS/Support
Identifier:            Support
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2022-07-08 15:23:26.9864 -0400
OS Version:            macOS 12.4 (21F79)
Report Version:        12
Anonymous UUID:        878334E7-F282-ADC2-4AD7-1700BC2D42EE

Sleep/Wake UUID:       04870C30-C965-4DE9-A6F4-2FEDDE4ACA94

Time Awake Since Boot: 300000 seconds
Time Since Wake:       205192 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_MEMORY_ERROR at 0x0000000104affee0
Exception Codes:       0x000000000000000a, 0x0000000104affee0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [52471]

VM Region Info: 0x104affee0 is in 0x104adc000-0x104b48000;  bytes after start: 147168  bytes before end: 295199
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  mapped file                 104adc000-104b48000    [  432K] r-x/r-x SM=COW  ...ct_id=24f27c9
      mapped file                 104b48000-104b4c000    [   16K] r--/rw- SM=COW  ...ct_id=15313c9

Kernel Triage:
VM - Object is not alive


Thread 0 Crashed:
0   ???                           	       0x104affee0 ???
1   ???                           	       0x1ade7f6c8 ???
2   ???                           	       0x1ade7eb4c ???
3   ???                           	       0x1ade7e9dc ???
4   ???                           	       0x1adebee38 ???
5   ???                           	       0x1ade7fb14 ???
6   ???                           	       0x1ade7eb4c ???
7   ???                           	       0x1ade94e50 ???
8   ???                           	       0x1a7dd58f4 ???
9   ???                           	       0x1a7dd4084 ???
10  ???                           	       0x1a7dc6250 ???
11  ???                           	       0x1a7d9796c ???
12  ???                           	       0x104ae3418 ???
13  dyld                          	       0x104e5d08c start + 520

Thread 1:: com.apple.NSEventThread
0   ???                           	       0x1a51668b0 ???
1   ???                           	       0x1a52712b0 ???
2   ???                           	       0x1a526f760 ???
3   ???                           	       0x1a526eb24 ???
4   ???                           	       0x1a7f42374 ???
5   ???                           	       0x1a51a426c ???
6   ???                           	       0x1a519f08c ???

Thread 2:
0   ???                           	       0x1a519f078 ???


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000060000161a550   x1: 0x0000600002d30b40   x2: 0x0000000000000000   x3: 0x000000016b3225e8
    x4: 0x0000000000000010   x5: 0x000000016b3227f0   x6: 0x000000016b322d00   x7: 0x000060000232c4e0
    x8: 0x000060000161a560   x9: 0x0000000104affee0  x10: 0x01000001fdb302c1  x11: 0x02000001fdb302c1
   x12: 0x0000000000000015  x13: 0x0000000122020540  x14: 0x0000000000000000  x15: 0x00000001fdb2ad48
   x16: 0x00000001a502a4c0  x17: 0x00000001ff427c58  x18: 0x0000000000000000  x19: 0x000060000182b2e0
   x20: 0x0000600002d30b40  x21: 0x000000000000000a  x22: 0x000000016b322c90  x23: 0x0000000000000000
   x24: 0x000000016b322810  x25: 0x0000600003b7be30  x26: 0x0000000000000001  x27: 0x0000000000000003
   x28: 0x0000000000000000   fp: 0x000000016b322800   lr: 0x00000001a8365ad8
    sp: 0x000000016b3227e0   pc: 0x0000000104affee0 cpsr: 0x60001000
   far: 0x0000000104affee0  esr: 0x82000007 (Instruction Abort) Translation fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x104e58000 -        0x104eb7fff dyld (*) <d9c2a46e-8dc4-3950-9d6a-f799e8ccb683> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=608K resident=0K(0%) swapped_out_or_unallocated=608K(100%)
Writable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG image                            96K        6 
ColorSync                          544K       27 
CoreAnimation                     1456K       26 
CoreGraphics                        48K        3 
CoreUI image data                   80K        1 
Foundation                          16K        1 
Image IO                           112K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           265.5M       54 
MALLOC guard page                  288K       15 
MALLOC_MEDIUM (reserved)         720.0M        6         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                  192K        3 
STACK GUARD                       56.0M        3 
Stack                             9264K        3 
VM_ALLOCATE                       1168K       10 
__DATA                              16K        1 
__DATA_CONST                        96K        1 
__LINKEDIT                         224K        1 
__TEXT                             384K        1 
dyld private memory               1024K        1 
libnetwork                         128K        8 
mapped file                      331.6M       43 
shared memory                      864K       15 
===========                     =======  ======= 
TOTAL                              1.7G      234 
TOTAL, minus reserved VM space   669.1M      234 



-----------
Full Report
-----------

{"app_name":"Support","timestamp":"2022-07-08 15:23:28.00 -0400","app_version":"","slice_uuid":"75d765c1-9648-3b73-a058-44a6bc802602","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.4 (21F79)","incident_id":"B2D25DE7-E1F8-42AB-9D45-7E79003B6753","name":"Support"}
{
  "uptime" : 300000,
  "procLaunch" : "2022-07-08 09:57:13.4194 -0400",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 6790369242750,
  "coalitionID" : 15492,
  "osVersion" : {
    "train" : "macOS 12.4",
    "build" : "21F79",
    "releaseType" : "User"
  },
  "captureTime" : "2022-07-08 15:23:26.9864 -0400",
  "incident" : "B2D25DE7-E1F8-42AB-9D45-7E79003B6753",
  "bug_type" : "309",
  "pid" : 52471,
  "procExitAbsTime" : 7260150743988,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Support",
  "procPath" : "\/private\/var\/folders\/*\/Support.app\/Contents\/MacOS\/Support",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "nl.root3.support",
  "crashReporterKey" : "878334E7-F282-ADC2-4AD7-1700BC2D42EE",
  "wakeTime" : 205192,
  "sleepWakeUUID" : "04870C30-C965-4DE9-A6F4-2FEDDE4ACA94",
  "sip" : "enabled",
  "vmRegionInfo" : "0x104affee0 is in 0x104adc000-0x104b48000;  bytes after start: 147168  bytes before end: 295199\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  mapped file                 104adc000-104b48000    [  432K] r-x\/r-x SM=COW  ...ct_id=24f27c9\n      mapped file                 104b48000-104b4c000    [   16K] r--\/rw- SM=COW  ...ct_id=15313c9",
  "isCorpse" : 1,
  "exception" : {"codes":"0x000000000000000a, 0x0000000104affee0","rawCodes":[10,4373610208],"type":"EXC_BAD_ACCESS","signal":"SIGBUS","subtype":"KERN_MEMORY_ERROR at 0x0000000104affee0"},
  "termination" : {"flags":0,"code":10,"namespace":"SIGNAL","indicator":"Bus error: 10","byProc":"exc handler","byPid":52471},
  "ktriageinfo" : "VM - Object is not alive\n",
  "vmregioninfo" : "0x104affee0 is in 0x104adc000-0x104b48000;  bytes after start: 147168  bytes before end: 295199\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  mapped file                 104adc000-104b48000    [  432K] r-x\/r-x SM=COW  ...ct_id=24f27c9\n      mapped file                 104b48000-104b4c000    [   16K] r--\/rw- SM=COW  ...ct_id=15313c9",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1611680,"threadState":{"x":[{"value":105553139443024},{"value":105553163651904},{"value":0},{"value":6093415912},{"value":16},{"value":6093416432},{"value":6093417728},{"value":105553153148128},{"value":105553139443040},{"value":4373610208},{"value":72057602589262529},{"value":144115196627190465},{"value":21},{"value":4865525056},{"value":0},{"value":8551312712},{"value":7063381184},{"value":8577514584},{"value":0},{"value":105553141609184},{"value":105553163651904},{"value":10},{"value":6093417616},{"value":0},{"value":6093416464},{"value":105553178639920},{"value":1},{"value":3},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7117101784},"cpsr":{"value":1610616832},"fp":{"value":6093416448},"sp":{"value":6093416416},"esr":{"value":2181038087,"description":"(Instruction Abort) Translation fault"},"pc":{"value":4373610208,"matchesCrashFrame":1},"far":{"value":4373610208}},"frames":[{"imageOffset":4373610208,"imageIndex":0},{"imageOffset":7212627656,"imageIndex":0},{"imageOffset":7212624716,"imageIndex":0},{"imageOffset":7212624348,"imageIndex":0},{"imageOffset":7212887608,"imageIndex":0},{"imageOffset":7212628756,"imageIndex":0},{"imageOffset":7212624716,"imageIndex":0},{"imageOffset":7212715600,"imageIndex":0},{"imageOffset":7111268596,"imageIndex":0},{"imageOffset":7111262340,"imageIndex":0},{"imageOffset":7111205456,"imageIndex":0},{"imageOffset":7111014764,"imageIndex":0},{"imageOffset":4373492760,"imageIndex":0},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":1}]},{"id":1611757,"name":"com.apple.NSEventThread","frames":[{"imageOffset":7064676528,"imageIndex":0},{"imageOffset":7065768624,"imageIndex":0},{"imageOffset":7065761632,"imageIndex":0},{"imageOffset":7065758500,"imageIndex":0},{"imageOffset":7112762228,"imageIndex":0},{"imageOffset":7064928876,"imageIndex":0},{"imageOffset":7064907916,"imageIndex":0}]},{"id":1763956,"frames":[{"imageOffset":7064907896,"imageIndex":0}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4377116672,
    "size" : 393216,
    "uuid" : "d9c2a46e-8dc4-3950-9d6a-f799e8ccb683",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7061602304,
  "size" : 3136077824,
  "uuid" : "513553bb-5ca5-3b9e-a613-b0603ffe3038"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=608K resident=0K(0%) swapped_out_or_unallocated=608K(100%)\nWritable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG image                            96K        6 \nColorSync                          544K       27 \nCoreAnimation                     1456K       26 \nCoreGraphics                        48K        3 \nCoreUI image data                   80K        1 \nFoundation                          16K        1 \nImage IO                           112K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           265.5M       54 \nMALLOC guard page                  288K       15 \nMALLOC_MEDIUM (reserved)         720.0M        6         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  192K        3 \nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                       1168K       10 \n__DATA                              16K        1 \n__DATA_CONST                        96K        1 \n__LINKEDIT                         224K        1 \n__TEXT                             384K        1 \ndyld private memory               1024K        1 \nlibnetwork                         128K        8 \nmapped file                      331.6M       43 \nshared memory                      864K       15 \n===========                     =======  ======= \nTOTAL                              1.7G      234 \nTOTAL, minus reserved VM space   669.1M      234 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "628bd2fda5168570b594bb52"
      },
      "deploymentId" : 240000135
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "62c4376c87beda2658c8f47d"
      },
      "deploymentId" : 240000178
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by everetteallen** [comment] 2022-07-13 13:18
Config Profile I am using 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Title</key>
    <string>Serial No. $SERIALNUMBER</string>
    <key>StatusBarIconNotifierEnabled</key>
    <true/>
    <key>CustomColor</key>
    <string>#CC0000</string>
    <key>HideFirstRow</key>
    <false/>
    <key>HideSecondRow</key>
    <false/>
    <key>ShowWelcomeScreen</key>
    <false/>
    <key>FooterText</key>
    <string>Provided for $REALNAME by OIT with ❤️</string>
    <key>InfoItemOne</key>
    <string>ComputerName</string>
    <key>InfoItemTwo</key>
    <string>MacOSVersion</string>
    <key>InfoItemThree</key>
    <string>Storage</string>
    <key>InfoItemFour</key>
    <string>Password</string>
    <key>InfoItemFive</key>
    <string>Network</string>
    <key>InfoItemSix</key>
    <string>ExtensionA</string>
    <key>PasswordExpiryLimit</key>
    <integer>5</integer>
    <key>PasswordType</key>
    <string>KerberosSSO</string>
    <key>PasswordLabel</key>
    <string>Unity Password</string>
    <key>FirstRowTitleLeft</key>
    <string>Contact NCSU Help Desk</string>
    <key>FirstRowSubtitleLeft</key>
    <string>Click or Call 919-515-HELP</string>
    <key>FirstRowTypeLeft</key>
    <string>URL</string>
    <key>FirstRowLinkLeft</key>
    <string>https://ncsu.service-now.com/sp?id=index</string>
    <key>FirstRowSymbolLeft</key>
    <string>wrench.and.screwdriver.fill</string>
    <key>FirstRowTypeMiddle</key>
    <string>App</string>
    <key>FirstRowTitleRight</key>
    <string>Self Service</string>
    <key>FirstRowSubtitleRight</key>
    <string>Click to Open Self Service</string>
    <key>FirstRowTypeRight</key>
    <string>App</string>
    <key>FirstRowLinkRight</key>
    <string>com.jamfsoftware.selfservice.mac</string>
    <key>FirstRowSymbolRight</key>
    <string>cart.badge.plus</string>
    <key>SecondRowTitleLeft</key>
    <string>Apple User Group</string>
    <key>SecondRowTypeLeft</key>
    <string>URL</string>
    <key>SecondRowLinkLeft</key>
    <string>https://go.ncsu.edu/mac</string>
    <key>SecondRowSymbolLeft</key>
    <string>person.fill</string>
    <key>SecondRowTitleMiddle</key>
    <string>NCSU Home Page</string>
    <key>SecondRowTypeMiddle</key>
    <string>URL</string>
    <key>SecondRowLinkMiddle</key>
    <string>https://www.ncsu.edu</string>
    <key>SecondRowSymbolMiddle</key>
    <string>house.fill</string>
    <key>SecondRowTitleRight</key>
    <string>Google Drive</string>
    <key>SecondRowTypeRight</key>
    <string>URL</string>
    <key>SecondRowLinkRight</key>
    <string>https://ncsu.drive.google.com</string>
    <key>SecondRowSymbolRight</key>
    <string>externaldrive.connected.to.line.below.fill</string>
    <key>ExtensionTitleA</key>
    <string>Your Email is $EMAIL</string>
    <key>ExtensionSymbolA</key>
    <string>envelope.fill</string>
    <key>ExtensionTypeA</key>
    <string>URL</string>
    <key>ExtensionLinkA</key>
    <string>https://gmail.ncsu.edu</string>
    <key>ExtensionTypeB</key>
    <string>App</string>
  </dict>
</plist>

**Comment by martinvandiemen** [comment] 2022-10-20 12:53
Please let us know if you're still experiencing this issue. We're unable to reproduce this. I'll close this for now.

**Closed by martinvandiemen** 2022-10-20 12:53 UTC
Labels: bug
