### ISSUE TITLE
Users presented with macOS Sonoma even if it's deferred

### ISSUE THREAD

**Issue by built2order** [root3nl/SupportApp#149] opened 2023-09-27 12:49 UTC
Users are presented with an upgrade to macOS Sonoma option through SupportApp even though an MDM based deferral policy is in place and enforced. Users who click on the version are navigated to System Settings however no upgrade is available due to this deferral policy.

<img width="531" alt="MicrosoftTeams-image (12)" src="https://github.com/root3nl/SupportApp/assets/6132811/5d922f9f-b22f-4b30-8587-f2afd918bcac">

**Comment by martinwen1990** [comment] 2023-09-27 13:43
same her...need a fix for this. THX

**Comment by meta-github** [comment] 2023-09-27 13:45
I can only support this request. It is very unfortune from a users perspective that an alert / notification is displayed, but no update can be installed. I understand that the cause of the alert / notification are the preferences of softwareupdate, which show the update even though it is deferred, but a solution would be cool.

**Comment by meta-github** [comment] 2023-09-27 13:56
As a workaround, we are now using key config key `HideMajorUpdates`. While an automatic solution would be easier to handle, this is still a good help for us at the moment.

**Comment by jordywitteman** [comment] 2023-09-27 14:01
Hi, please refer to the documentation and search for `HideMajorUpdates`. This is the current way (same a last year) to hide the new major macOS version. The app looks at this preference domain `/Library/Preferences/com.apple.SoftwareUpdate.plist` and nothing is in there to detect the configured deferral and all updates (even deferred) are shown in this plist. Open to any suggestions if anyone was able to find the available updates as shown in System Settings.

**Comment by meta-github** [comment] 2023-09-27 14:57
We just have submitted a feedback to apple that an API to query updates _as visible in system settings_ is needed and we will also open an enterprise care ticket for this issue.

**Comment by diwanicki** [comment] 2023-09-27 16:51
HideMajorUpdates key is not working for me. I haven’t announced this feature to my users, but eventually someone is going to notice the red pip

**Comment by jordywitteman** [comment] 2023-10-17 07:00
Resolved with v2.5.1 and `HideMajorUpdates` no longer needed

**Closed by jordywitteman** 2023-10-17 07:00 UTC
Labels: documentation, help wanted
