### ISSUE TITLE
Ventura bug when clicking on "Last Reboot" button

### ISSUE THREAD

**Issue by xirianlight** [root3nl/SupportApp#84] opened 2022-08-29 20:10 UTC
Hey folks! Testing in 13.0 b6.

If you click on the "Last Reboot" button, the following occurs:

1. SupportApp hides the main app
2. The popup window with message appears for about 0.5 seconds and then disappears
3. At this point the whole app is hidden
4. If you click on the menu bar item, the popup and main app both appear again
5. Clicking the OK button closes the popup, and then hides the main app

I'm hoping this could be amended so that summoning the popup window doesn't close the rest of the app, and that it would remain visible until dismissed?

Thanks!

**Comment by jordywitteman** [comment] 2022-08-30 07:27
Hi @xirianlight! This will be resolved in version 2.4.1 planned for today and we'll be using a different implementation instead of a standard alert because something has changed. We filed feedback with Apple but is seems it's expected behaviour.

**Comment by jordywitteman** [comment] 2022-08-30 19:35
This should now be resolved in 2.4.1

**Closed by jordywitteman** 2022-08-30 19:35 UTC

**Comment by xirianlight** [comment] 2022-08-30 20:55
Amazing turnaround, thanks for your work on such a stellar project.
